### ISSUE TITLE
HA 2024.5.0 deprecation warning

### ISSUE THREAD

**Issue by Intecpsp** [ydogandjiev/hass-sutro#106]
`Detected that custom integration 'sutro' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/sutro/__init__.py, line 54: hass.async_add_job(, please create a bug report at https://github.com/ydogandjiev/hass-sutro/issues`

**Comment by Intecpsp** [comment]
Looking further, I also found this:

`TEMP_FAHRENHEIT was used from sutro, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'sutro' custom integration`

**Comment by ydogandjiev** [comment]
Issue has been fixed in v0.0.8:
https://github.com/ydogandjiev/hass-sutro/releases/tag/v0.0.8
