### ISSUE TITLE
calls async_forward_entry_setup which is deprecated and will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by wez** [ydogandjiev/hass-sutro#158]
Home Assistant is reporting:

Detected that custom integration 'sutro' calls async_forward_entry_setup for integration, sutro ...  which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/sutro/__init__.py, line 53: hass.async_create_task(, please create a bug report at https://github.com/ydogandjiev/hass-sutro/issues

I'm running version 0.0.9

**Comment by ydogandjiev** [comment]
Addressed in v1.0.0-beta.0:
https://github.com/ydogandjiev/hass-sutro/releases/tag/v1.0.0-beta.0

@wez, please consider updating to v1.0.0-beta.0 and confirming that you no longer see the issue and everyhing works as expected.
