### ISSUE TITLE
Not able to find token in request when using Charles

### ISSUE THREAD

**Issue by Intecpsp** [ydogandjiev/hass-sutro#19]
## Version of the custom_component
0.0.1

## Configuration

None to supply

## Describe the bug

I am unable to find any reference to `https://api.mysutro.com/graphql` when sending my traffic through Charles. I can only find `https://api.mysutro.com/` and even in those, I am unable to find any Authorization header information. Can the documentation around retrieving this token be expanded upon to help those of us who aren't familiar with sniffing traffic?

## Debug log

None to supply

**Comment by ydogandjiev** [comment]
@Intecpsp, are you using the Sutro app for iPhone and did you set Charles as the proxy for your phone? If you go to Help > SSL Proxying > Install Charles Root Certification on a Mobile Device or Remote Browser in Charles you should be able to get instructions for what you need to do:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/3357245/185007909-9bd6df52-985d-49fb-9fef-9081614dae81.png">

Something like this:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/3357245/185007929-aeb29124-4dfa-42af-bf29-1ad1be4d7257.png">

After configuring the proxy and installing the SSL certs, you need to open the Sutro app on your iPhone and observe the traffic in Charles. It should look something like this:
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/3357245/185008426-45ff8082-3b2a-458f-abcc-87a7cfb3ca89.png">

Alternatively, you can try the method described here:
https://community.home-assistant.io/t/sutro-integration/442908/3

**Comment by Intecpsp** [comment]
That got it for me (curl command)! Thank you!
