### ISSUE TITLE
Use login credentials in order to obtain the api token.

### ISSUE THREAD

**Issue by wonderslug** [ydogandjiev/hass-sutro#23]
**Is your feature request related to a problem? Please describe.**

The mechanism to obtain the API token is kinda difficult with either the Charles proxy example, or for HA users that are not experienced on the command line for the curl call example.

**Describe the solution you'd like**

Changes could be made to the config flow to take in the Sutro credentials and use them to make the HTTP call equivalent to the following curl call

```bash
curl --header "Content-Type: application/json" --compressed --header "Connection: Keep-Alive" --user-agent "okhttp/3.12.1" --data-binary '{"operationName":null,"variables":{"email":"EMAIL","password":"PASSWORD","focusedInput":"","loading":false},"query":"mutation ($email: String!, $password: String!) {\n login(email: $email, password: $password) {\n user {\n firstName\n lastName\n email\n phone\n releaseGroup\n __typename\n }\n token\n __typename\n }\n}\n"}' https://api.mysutro.com/graphql
```

This would allow the Token thats returned from the call to be directly captured and used for the configuration of the integration without the HA user having to do anything else.

**Describe alternatives you've considered**

Keep Charles Proxy or curl call options.

**Additional context**
NA

**Comment by bshep** [comment]
I made a similar integration for my own use ( its not as polished as this one and I dont have time for support ) however I made a script to get the token, may be easier for some people, link below:

It requires use of the `jq` command to be able to parse the returned json. And the `curl` command to issue the http request.

Click here to get it: [getToken.sh](https://github.com/bshep/mysutro-integration/blob/5825d700d0ef9593e2fedcb61fc83709e5e3edec/custom_components/scripts/getToken.sh)

**Comment by wez** [comment]
Please update the readme to reflect that charles is no longer needed for this; I spent 15 minutes trying to set that up before I found this issue and the script mentioned here, only to find that the token I extracted by hand wasn't required any more!
