### ISSUE TITLE
Allow users to view and complete recommendations from within the integration

### ISSUE THREAD

**Issue by lukeclopez-al** [ydogandjiev/hass-sutro#67]
**Is your feature request related to a problem? Please describe.**
Not a problem, just requesting additional functionality.

**Describe the solution you'd like**
Provide a way for users to see recommendations and mark them as complete once they've used the chemicals. The latest recommendations can be viewed by adding a few lines to the `me` query:
```
        {
            me {
                id
                firstName
                device {
                    batteryLevel
                    serialNumber
                    temperature
                    cartridgeCharges
                    health
                    coreStatus
                    lidOpen
                    online
                    shouldTakeReadings
                    lastMessage
                    currentFirmwareVersion
                }
                hub {
                    online
                    chargerStatus
                    ssid
                    lastMessage
                }
                pool {
                       ####  New Stuff Below This Line ####
                        latestRecommendations {
                          conflictWarning
                          recommendations {
                            id
                            chemical {
                              behaviour
                              image
                              name
                              types
                              packageSize
                              packageSizeUnit
                              upc
                            }
                            completedAt
                            expiredAt
                            type
                            decision
                            explanation
                            treatment
                          }
                      }
                    ####  New Stuff Above This Line ####
                    latestReading {
                        alkalinity
                        bromine
                        chlorine
                        ph
                        readingTime
                    }
                }
            }
        }
```

Recommendations can be completed with this mutation:
```
mutation ($recommendationId: ID!, $completedAt: DateTime) {
  completeRecommendation(recommendationId: $recommendationId, completedAt: $completedAt) {
    success
    completedAt
  }
}
```

And these params:
```
{
	"recommendationId": "245043",
	"completedAt": "2021-03-05T00:32:40.000Z"
}
```

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ydogandjiev** [comment]
@lukeclopez-al, is there an easy way for me to simulate some of these recommendations for testing purposes? Maybe using a test account of some sort?

**Comment by lukeclopez-al** [comment]
@ydogandjiev I could give you access to a testing account that has numerous readings/recommendations generated already

**Comment by ydogandjiev** [comment]
@lukeclopez-al, how does the Sutro app generate these strings:
![image](https://user-images.githubusercontent.com/3357245/235365759-42257089-c71a-4842-a0f0-5df516e6fe6f.jpeg)

I don't see them in the GraphQL response for the updated query you shared. Is this string generated client-side based on the type and decisions properties of the recommendation?

**Comment by wonderslug** [comment]
Here is an example of them im getting as im opening my pool for the season :)

```json
{
    "data": {
        "me": {
            "device": {
                "batteryLevel": 87,
                "cartridgeCharges": 67,
                "coreStatus": true,
                "currentFirmwareVersion": "2.1.7",
                "health": "GOOD",
                "lastMessage": "2023-05-03T00:08:45Z",
                "lidOpen": false,
                "online": true,
                "serialNumber": "xxxxxxxxxxxxxxx",
                "shouldTakeReadings": true,
                "temperature": 75.9
            },
            "firstName": "xxxx",
            "hub": {
                "chargerStatus": "CHARGED",
                "lastMessage": "2023-05-03T00:08:45Z",
                "online": true,
                "ssid": "xxxxxxxxx"
            },
            "id": "xxxx",
            "pool": {
                "latestReading": {
                    "alkalinity": 150.5,
                    "bromine": null,
                    "chlorine": 1.04,
                    "ph": 6.85,
                    "readingTime": "2023-05-02T23:23:19Z"
                },
                "latestRecommendations": {
                    "conflictWarning": "",
                    "recommendations": [
                        {
                            "chemical": {
                                "behaviour": "saltwater_generator",
                                "image": null,
                                "name": "Saltwater Generator",
                                "packageSize": null,
                                "packageSizeUnit": null,
                                "types": [
                                    "PRIMARY_SANITIZER"
                                ],
                                "upc": "generic_saltwater_generator"
                            },
                            "completedAt": null,
                            "decision": "LOW",
                            "expiredAt": null,
                            "explanation": "It will make your swimming water safe and clean.",
                            "id": "4505579",
                            "treatment": "Adjust your Saltwater Generator to raise your chlorine level.",
                            "type": "CHLORINE"
                        },
                        {
                            "chemical": {
                                "behaviour": "sodium_carbonate",
                                "image": null,
                                "name": "pH up / Soda ash",
                                "packageSize": null,
                                "packageSizeUnit": null,
                                "types": [
                                    "PH_UP"
                                ],
                                "upc": "generic_sodium_carbonate"
                            },
                            "completedAt": null,
                            "decision": "LOW",
                            "expiredAt": null,
                            "explanation": "It will prevent corrosion of your spa surface and equipment.",
                            "id": "4505580",
                            "treatment": "Broadcast 2 cups and 1 half cup of pH up / Soda ash.",
                            "type": "PH"
                        }
                    ]
                }
            }
        }
    }
}
```

I think we could add this just by putting this as a recommendations sensor, and having the actual recommendations be a well formatted attribute array. Should be easy just to drop that json in there.

If I get some time this week I will look at adding it.

**Comment by wonderslug** [comment]
@lukeclopez-al do you have any examples of the conflictWarning?

**Comment by lukeclopez-al** [comment]
> @lukeclopez-al, how does the Sutro app generate these strings: ![image](https://user-images.githubusercontent.com/3357245/235365759-42257089-c71a-4842-a0f0-5df516e6fe6f.jpeg)
> 
> I don't see them in the GraphQL response for the updated query you shared. Is this string generated client-side based on the type and decisions properties of the recommendation?

Yes, these are made on the client side based on the properties of the recommendation.

**Comment by lukeclopez-al** [comment]
> @lukeclopez-al do you have any examples of the conflictWarning?

The only one that exists right now is: `"Wait an hour between any chemical additions."` @wonderslug

**Comment by wonderslug** [comment]
@lukeclopez-al so just a string message if one is needed. thanks.

**Comment by wonderslug** [comment]
So looking at this its fairly easy to get the recommendations and setup a binary sensor if there are recommendations and attach the recommends and conflictWarning structure itself to the attributes.

Im not sure about this though, I think there might be a better/other way to handle this.

Putting this structure as an attribute allows a user to grab them and present them how ever they want.
Im not sure we want to try to start dynamically creating entities for a recommendation, as it would really just need to be a sensor with the same structure attached to attributes. Im wanting to get some thoughts on this.

We can easily do a service for completing a recommendation all that really takes is the id for the recommendation itself.  It would allow HA users to do their own setup with a button or something and just pass the id if the recommendation to service.

Thoughts?

**Comment by ydogandjiev** [comment]
@wonderslug, that sounds like the perfect design! I spent a lot of time trying to figure out how to best model this information in Home Assistant; not sure why a binary sensor didn't come to mind. I assume it would be triggered when there is a recommendation and clear when everything is good, right?

**Comment by wonderslug** [comment]
Yeah only trigger true as Problem device class when there are recommendations present.  Once they are cleared (I think) or not present it would be false/cleared.

**Comment by ydogandjiev** [comment]
Added support for viewing and completing recommendations in v1.0.0-beta.0:
https://github.com/ydogandjiev/hass-sutro/releases/tag/v1.0.0-beta.0

I modeled it as a todo list. Checking off the recommendations marks them as completed. They can also be uncompleted by unchecking them in the list:
![image](https://github.com/user-attachments/assets/69119855-d7ee-458a-ac10-21f328883050)
![image](https://github.com/user-attachments/assets/c4ce1e25-ed1f-4052-a6f0-5b7004406782)

@lukeclopez-al, @wonderslug, please give it a shot and let me know if you have any feedback.
